apiVersion: v1
kind: Secret
metadata:
  name: y2ks-secrets
type: Opaque
stringData:
  SQS_QUEUE_URL: "https://sqs.{{ .Values.region }}.amazonaws.com/{{ .Values.accountId | toString }}/{{ .Values.queueName }}"
  DDB_TABLE: "{{ .Values.ddbTable }}"
  ADMIN_TOKEN: "{{ .Values.adminToken }}"
  GRAFANA_PASSWORD: "{{ .Values.grafanaPassword }}"
