apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-kinesis-stream-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: y2ks-worker
  minReplicaCount: {{ .Values.worker.minReplicas }}
  maxReplicaCount: {{ .Values.worker.maxReplicas }}
  triggers:
  - type: aws-kinesis-stream
    metadata:
      identityOwner: operator
      streamName: "{{ .Values.kinesisStreamName }}"
      shardCount: "{{ .Values.worker.shardCount }}"
      awsRegion: "{{ .Values.region }}"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-aws-credentials
  namespace: default
spec:
  podIdentity:
    provider: aws-eks
