apiVersion: apps/v1
kind: Deployment
metadata:
  name: y2ks-worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: worker-sa
      priorityClassName: y2ks-normal
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values: ["spot"]
      containers:
      - name: worker
        image: "{{ .Values.images.worker }}"
        command: ["python", "-u"]
        args: ["/app/worker.py"]
        livenessProbe:
          exec:
            command: ["python", "-c", "import os, sys; sys.exit(0 if os.path.exists('/tmp/worker_alive') else 1)"]
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 3
        resources:
          requests:
            cpu: 500m  # LYK가 200m으로 낮췄으나 원래 설계값으로 복원
            memory: 400Mi
          limits:
            cpu: 700m
            memory: 512Mi
        env:
        - name: TICKET_COUNT
          value: "{{ .Values.ticketCount }}"
        - name: SQS_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: SQS_QUEUE_URL
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: AWS_REGION
        - name: DDB_TABLE
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: DDB_TABLE
        volumeMounts:
        - name: code-volume
          mountPath: /app
      volumes:
      - name: code-volume
        configMap:
          name: y2ks-app-code
